### ISSUE TITLE
Option to build either versions of MOM (versions: 5 and 6)

### ISSUE THREAD

**Issue by sanAkel** [GEOS-ESM/GEOSgcm_GridComp#24]
Could an option (or something to that effect) be added so that we can build either MOM5 (using the MOM_GEOS5PlugMod.F90 - MOM5 plug) or the new (MOM6 plug).

**Comment by aerorahul** [comment]
@sanAkel 
in `src/Components/@GEOSgcm_GridComp/GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/CMakeLists.txt`, you could add:

```
# Default build with MOM5
option( BUILD_WITH_MOM6 "Build with MOM6" OFF )

if( BUILD_WITH_MOM6 )
  set( subcomponents MOM6_GEOSPlugMod )
elseif( BUILD_WITH_MOM6 )
  set( subcomponents MOM_GEOS5PlugMod )
endif(BUILD_WITH_MOM6 )

add_subdirectory( ${subcomponents} )
```

When building at the top `cmake -DBUILD_WITH_MOM6=ON` to build with MOM6.

**Comment by mathomp4** [comment]
@aerorahul It might be "cleaner" to perhaps have `-DMOM_VERSION=MOM5` or the like instead. Just because the opposite of MOM6 might not be obviously MOM5. But it all amounts to the same thing in the end.

That said, I think a lot of the build issues @sanAkel (which I'll talk with @tclune) can be "fixed" by essentially having two plugs and managing the build better. I was just dumb/lazy when I was first working with @sanAkel and he lost a good few hours because of some interface clashing.

With two plugs (and the right machinery above with `MAPL_GetResource`) then we should build both and let the user decide at run time.

**Comment by aerorahul** [comment]
@mathomp4 
I agree with having 2 plugs; distinct for the two MOM's.  I discussed this with @sanAkel and showed him how I had it configured.  I will work with him before a PR is issued.  It may not be obvious from the pseudo-code above, but two plugs is the result of it.  It can be extended to any number of ocean-models, all self-contained and configured at build time.

**Comment by sanAkel** [comment]
#70 includes/address THIS issue. So closing it
