### ISSUE TITLE
Nightly test for GCM using CatchCN

### ISSUE THREAD

**Issue by gmao-rreichle** [GEOS-ESM/GEOSgcm_GridComp#242]
GCM gatekeepers and CatchCN users:
(@wmputman @sdrabenh @elee15 @smahanam @weiyuan-jiang @gmao-jkolassa  
[apparently missing on github: Randy, Lesley] )

The GCM suite of tests does not currently check for 0-diff in CatchCN.
During review of pull request #208 (later replaced with #240), a bug was discovered in CatchCN that could have been a major problem later on.  This bug would have been discovered in a 0-diff test with CatchCN.
There are two options: 
1. Add a GCM test for CatchCN.
2. Make the GEOSldas tests mandatory for GCM developers if there are any changes in Catch or CatchCN.  (CatchCN is included in the GEOSldas suite of tests -- see also issue #243.)

**IMPORTANT**:  Because CatchCN was not tested for an extended period, it is possible that the current github ("develop") version of CatchCN has diverged from the version of CatchCN that was used for science publications.  That is, someone also needs to establish that the CatchCN version in github is still accurate in terms of science.

**Comment by mathomp4** [comment]
@gmao-rreichle I'm thinking I can make a test for catchcn, but I would need restarts for it. I'm guessing like `catch_internal_rst`, `catchcn_internal_rst` is not an optional restart that can be bootstrapped? And since I usually get my restarts from MERRA2 and it didn't use CatchCN, I don't carry them in my "standard suite".  And, of course, it would need to run at c24 and hopefully not be too expensive.

And then I'd have to know how to setup and run it (aka how to answer `gcm_setup`).

**Comment by gmao-rreichle** [comment]
@mathomp4 : Many thanks for offering to help.  At this stage, the modeling group will need to decide how they want to go about it and come up with a suitable test run.  Once that exists, we'll need your help to implement it in the nightly suite.  It may take a while.

**Comment by gmao-rreichle** [comment]
pinging @rdkoster

**Comment by gmao-rreichle** [comment]
At a meeting on 13 Apr 2020, it was decided that a test for the GCM with CatchCN will be considered when GEOS ops are closer to running CatchCN.   In the meantime, the team will rely on the GEOSldas test for CatchCN.  
In conjunction with #243 , this approach should adequately prevent inadvertent modifications of  CatchCN.
