### ISSUE TITLE
multiple versions of CatchCN desired

### ISSUE THREAD

**Issue by JustinPerket** [GEOS-ESM/GEOSgcm_GridComp#41]
@smahanam and @fwzeng want to develop CatchCN with both CLM.4.0 and CLM4.5 BGC. They currently have functioning code for both. Unfortionally there's heavy duplications of file and subroutine names between their versions.

The quickest route to begin science development would be for them to create in their branch, a couple of the GEOSCatchCN_GridComp directory for 4.5. However, this would be undesirable to push to ldas's branch, or develop.

GEOSCatchCN_GridComp  could have subdirectories clm4.0 and clm4.5. Would it be possible to have either a build option or run-time resource option to select?

**Comment by smahanam** [comment]
Maybe a build option is the way.

CATCHCN uses dynamic vegetation, and Carbon and Nitrogen parameterization schemes from CLM.  CATCHCN's sub-surface hydrology, snow and turbulence schemes are as same as those of  CATCH.  It has its own surface energy scheme. CATCHCN has been using CLM4's DYNVEG, Carbon and Nitrogen parameterization since its implementation. 

We are merely upgrading CLM4 routines to CLM4.5's - the rest remains the same. Once updated, CLM4 routines will be obsolete at some point. We will just need to keep an option for those who want to use "old" CLM4 codes mainly during the transition period. 
In old GNUmakefiles  we could use a directive like $(D)USE_CLM4 and build CLM4 codes if the argument is passed when the model is being compiled.

Creating GEOScatchCN4.5_GridComp is undesirable because I thought GCs are for distinctly different models. We are merely upgrading few parameterizations that we copy from CLM. For e.g. we updated our snow scheme to incorporate impact of dust and black carbon on snow (that came with new prognostic variables as well), but we did not create new GCs for that.
If we add NoahMP, CLM itself, VIC or some other new land surface model, we sure can open a new GC. 
My 2cnts.

**Comment by tclune** [comment]
I'm sure I'm only half-understanding the issues here.  But my 2 cents:

Ideally we could instead just consider the new version the development branch and the old version the master branch.   But this thread would not exist if that option was workable.

If we want to be able to use both versions without complicating the externals configuration (any further than it already is), then some sort of CMake switch to toggle between the two versions seems to be preferable.      This could involve 2 directories or just slightly differently named files or even really large source files with a big `#ifdef` in them.   I defer to the people that have to live with the decision as to which is the most palatable.    I only ask that we aggressively clean up everything once the need to support both versions goes away.

**Comment by gmao-jkolassa** [comment]
Commenting here with cc to additional people to bring this issue to their attention. We are planning on submitting a PR addressing this issue in the near future. 

cc: @wmputman , @sdrabenh , @gmao-rreichle , @rdkoster , @biljanaorescanin , @smahanam , @weiyuan-jiang
